services:
  rabbitmq-mensageria:
    image: tulioufsm/projeto-sid:rabbitmq-mensageria-1.0.0
    container_name: rabbitmq-mensageria
    environment:
      RABBIT_DEFINITIONS: rabbit_definitions.json
    ports:
      - "15672:15672"
      - "5672:5672"

  redis-service:
    image: tulioufsm/projeto-sid:redis-1.0.0
    container_name: redis-service
    ports:
      - "6379:6379"

  gateway:
    image: tulioufsm/projeto-sid:gateway-1.0.0
    container_name: gateway
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq-mensageria
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      - rabbitmq-mensageria
      - redis-service
    ports:
      - "9991:9991"

  consulta:
    image: tulioufsm/projeto-sid:consulta-1.0.0
    container_name: consulta
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq-mensageria
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_REDIS_HOST: redis-service
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: trabalho_sid
    depends_on:
      - rabbitmq-mensageria
      - redis-service
    ports:
      - "9992:9992"

  saque:
    image: tulioufsm/projeto-sid:saque-1.0.0
    container_name: saque
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq-mensageria
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_REDIS_HOST: redis-service
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: trabalho_sid
    depends_on:
      - rabbitmq-mensageria
      - redis-service
    ports:
      - "9993:9993"
