services:
  rabbitmq:
    image: tulioufsm/microsservicos-financeiro-demo:rabbitmq-1.0.0
    container_name: rabbitmq
    environment:
      RABBIT_DEFINITIONS: rabbit_definitions.json
    ports:
      - "15672:15672"
      - "5672:5672"

  redis:
    image: tulioufsm/microsservicos-financeiro-demo:redis-1.0.0
    container_name: redis
    ports:
      - "6379:6379"

  gateway:
    image: tulioufsm/microsservicos-financeiro-demo:gateway-1.0.0
    container_name: gateway
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      - rabbitmq
      - redis
    ports:
      - "9991:9991"

  consulta:
    image: tulioufsm/microsservicos-financeiro-demo:consulta-1.0.0
    container_name: consulta
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_REDIS_HOST: redis-service
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: trabalho_sid
    depends_on:
      - rabbitmq
      - redis
    ports:
      - "9992:9992"

  saque:
    image: tulioufsm/microsservicos-financeiro-demo:saque-1.0.0
    container_name: saque
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_REDIS_HOST: redis-service
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: trabalho_sid
    depends_on:
      - rabbitmq
      - redis
    ports:
      - "9993:9993"

